# NOTE: Generated By HttpRunner v3.1.6
# FROM: create-user.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseCreateUser(HttpRunner):

    config = Config("global variable").variables(
        **{
            "host": "",
            "username": "",
            "password": "",
            "status_code": "",
            "body_status": "",
            "body_msg": "",
        }
    )

    teststeps = [
        Step(
            RunRequest("create user")
            .post("${host}/user")
            .with_headers(
                **{
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "Content-Type": "application/x-www-form-urlencoded",
                }
            )
            .with_data("username=${username}")
            .validate()
            .assert_equal("status_code", "${status_code}")
            .assert_equal("body.status", "${body_status}")
            .assert_equal("body.msg", "user ${username} create success.")
        ),
    ]


if __name__ == "__main__":
    TestCaseCreateUser().test_start()
