# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/login-api-v3-parameters-kvbind.yml


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLoginApiV3ParametersKvbind(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {
                "username-password-status_code-body_status-body_msg": [
                    ["zhangsan", "zhangsan123", 200, 200, "login success"],
                    ["lisi", "lisi123", 200, 400, "login error"],
                ]
            }
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("login parameters v3").variables(
        **{"host": "http://127.0.0.1:8888"}
    )

    teststeps = [
        Step(
            RunRequest("login")
            .post("${host}/login")
            .with_headers(
                **{
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "Content-Type": "application/x-www-form-urlencoded",
                }
            )
            .with_data("username=${username}&password=${password}")
            .validate()
            .assert_equal("status_code", "${status_code}")
            .assert_equal("body.status", "${body_status}")
            .assert_equal("body.msg", "${body_msg}")
        ),
    ]


if __name__ == "__main__":
    TestCaseLoginApiV3ParametersKvbind().test_start()
