# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/login-api-v3-variables-global.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLoginApiV3VariablesGlobal(HttpRunner):

    config = Config("global variable").variables(
        **{
            "host": "http://127.0.0.1:8888",
            "username": "zhangsan",
            "password": "zhangsan123",
            "status_code": 200,
            "body_status": 200,
            "body_msg": "login success",
        }
    )

    teststeps = [
        Step(
            RunRequest("login")
            .post("${host}/login")
            .with_headers(
                **{
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "Content-Type": "application/x-www-form-urlencoded",
                }
            )
            .with_data("username=${username}&password=${password}")
            .validate()
            .assert_equal("status_code", "${status_code}")
            .assert_equal("body.status", "${body_status}")
            .assert_equal("body.msg", "${body_msg}")
        ),
    ]


if __name__ == "__main__":
    TestCaseLoginApiV3VariablesGlobal().test_start()
