# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases/create-user-extract.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseCreateUserExtract(HttpRunner):

    config = Config("testcases module variable")

    teststeps = [
        Step(
            RunRequest("login")
            .with_variables(
                **{
                    "host": "http://127.0.0.1:8888",
                    "username": "zhangsan",
                    "password": "zhangsan123",
                    "status_code": 200,
                    "body_status": 200,
                    "body_msg": "login success",
                }
            )
            .post("${host}/login")
            .with_headers(
                **{
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "Content-Type": "application/x-www-form-urlencoded",
                }
            )
            .with_data("username=${username}&password=${password}")
            .extract()
            .with_jmespath("body.msg", "foo")
            .validate()
            .assert_equal("status_code", "${status_code}")
            .assert_equal("body.status", "${body_status}")
            .assert_equal("body.msg", "${body_msg}")
        ),
        Step(
            RunRequest("create user")
            .with_variables(
                **{
                    "host": "http://127.0.0.1:8888",
                    "username": "${foo}",
                    "status_code": 200,
                    "body_status": 200,
                    "body_msg": "user ${username} create success.",
                }
            )
            .post("${host}/user")
            .with_headers(
                **{
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "Content-Type": "application/x-www-form-urlencoded",
                }
            )
            .with_data("username=${username}")
            .validate()
            .assert_equal("status_code", "${status_code}")
            .assert_equal("body.status", "${body_status}")
            .assert_equal("body.msg", "${body_msg}")
        ),
    ]


if __name__ == "__main__":
    TestCaseCreateUserExtract().test_start()
