@startuml

start

:load fixture\n(session._fixturemanager._arg2fixturedefs);

:load testcase\n(session.items);

repeat :for item in session.items ;
    :execute fixtures\n(item.fixturenames);
    :execute testcase\n(item._pyfuncitem);
backward: 持续遍历;
repeat while ();

stop

@enduml