@startuml

start

:pytest.main;
:FixtureManager(session)\n(_pytest.fixtures.pytest_sessionstart);
repeat :hooks=[pytest_collection_modifyitems, \n            pytest_generate_tests, \n            pytest_plugin_registered]\n\nfor hook in hooks:;
    :pytest_plugin_registered\n(注册这个插件);
    :_maybe_apply_history\n(执行所有插件的pytest_plugin_registered的hook)\n;
    :self.parsefactories(plugin, nodeid)\n(将每个插件的fixture写入到FixtureManager._arg2fixturedefs);
repeat while ();

stop

@enduml