# NOTE: Generated By HttpRunner v3.1.6
# FROM: apis/list-users.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseListUsers(HttpRunner):

    config = Config("module variable").variables(
        **{"host": "", "status_code": "", "body_status": "", "body_msg": ""}
    )

    teststeps = [
        Step(
            RunRequest("list all users")
            .get("${host}/user")
            .with_headers(**{"User-Agent": "HttpRunner/${get_httprunner_version()}"})
            .validate()
            .assert_equal("status_code", "${status_code}")
            .assert_equal("body.status", "${body_status}")
            .assert_equal("body.msg", "${body_msg}")
        ),
    ]


if __name__ == "__main__":
    TestCaseListUsers().test_start()
