# NOTE: Generated By HttpRunner v3.1.6
# FROM: apis/login-api-v3-success.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLoginApiV3Success(HttpRunner):

    config = Config("login module variable")

    teststeps = [
        Step(
            RunRequest("login")
            .post("http://127.0.0.1:8888/login")
            .with_headers(
                **{
                    "User-Agent": "HttpRunner/${get_httprunner_version()}",
                    "Content-Type": "application/x-www-form-urlencoded",
                }
            )
            .with_data("username=zhangsan&password=zhangsan123")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.status", 200)
            .assert_equal("body.msg", "login success")
        ),
    ]


if __name__ == "__main__":
    TestCaseLoginApiV3Success().test_start()
